version: '3'

services:
  authentication:
    build:
      context: ./authentication
    ports:
      - "8001:8001"

  materials:
    build:
      context: ./materials
    ports:
      - "8002:8002"

  tests:
    build:
      context: ./tests
    ports:
      - "8003:8003"
